# Generated by Django 5.1.15 on 2026-08-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cover_letter', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('resume_public_id', models.CharField(max_length=255)),
                ('resume_url', models.URLField()),
            ],
        ),
    ]
